name: smart_medication
description: "Smart Medication Reminder Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_core_web: ^2.8.1
  firebase_auth: ^4.17.4
  firebase_auth_web: ^5.8.6
  cloud_firestore: ^4.15.4
  cloud_firestore_web: ^3.8.3
  flutter_local_notifications: ^17.1.2
  cupertino_icons: ^1.0.8
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  permission_handler_windows: ^0.2.1
  # android_alarm_manager_plus: ^3.0.4
  intl: ^0.18.0
  url_launcher: ^6.2.4
  url_launcher_windows: ^3.1.1
  image_picker: ^0.8.7+4
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
    # - assets/placeholder.png